gfx/env/leo_schoolbk.tga
gfx/env/leo_schooldn.tga
gfx/env/leo_schoolft.tga
gfx/env/leo_schoollf.tga
gfx/env/leo_schoolrt.tga
gfx/env/leo_schoolup.tga
maps/boost_shiyu.bsp
maps/boost_shiyu.res
models/cd/hb/1/cd_ch1.mdl
models/cd/maple/cd_ball.mdl
models/cd/maple/cd_balloon01.mdl
models/cd/maple/cd_bear03.mdl
models/cd/maple/cd_monster04.mdl
models/kzfun_leo/leo_burger.mdl
models/kzfun_leo/leo_heye.mdl
models/kzfun_leo/leo_hudie.mdl
models/kzfun_leo/leo_light_1.mdl
models/kzfun_leo/leo_lvzhi_02.mdl
models/kzfun_leo/leo_tuiche.mdl
sprites/kzfun_leo/sygg_cheming.spr
sprites/kzfun_leo/gg_xfyw.spr
