// cs_KVARTAL2.res - created with RESGen v2.0 BETA 3.
// RESGen is made by Jeroen "ShadowLord" Bogers.
// For more info go to http://resgen.hltools.com
// or E-mail me at resgen@hltools.com.

// .res entries (90):
rf.wad
editor_1.wad
kvartal_night.wad
kvartal_origin.wad
kvartal_outside.wad
kvartal_outside_foto.wad
gfx/env/grnplsnt_rotup.tga
gfx/env/grnplsnt_rotdn.tga
gfx/env/grnplsnt_rotlf.tga
gfx/env/grnplsnt_rotrt.tga
gfx/env/grnplsnt_rotft.tga
gfx/env/grnplsnt_rotbk.tga
models/props/dumpster_lidclosed_green.mdl
models/props/dumpster_lidclosed.mdl
models/props/truck_large-brown.mdl
models/props/jeep-russian.mdl
models/buzz/buzzer_teatp_ladasp.mdl
models/buzz/buzzer_teatp_toyota.mdl
models/buzz/buzzer_kt_gazel.mdl
models/chernobyl/furgon_kalash.mdl
models/props/light_bulb2.mdl
models/man/78rus_gazel_blue.mdl
models/man/78rus_ladasp.mdl
models/man/78rus_toyota_blue.mdl
models/chernobyl/budka_kalash.mdl
models/chernobyl/kotushka_kalash.mdl
models/props/pi_tree.mdl
models/buzz/buzzer_kt_derevse.mdl
models/man/grasd.mdl
models/props/topol-2.mdl
models/props/pi_tree3.mdl
models/props/pi_tree2.mdl
models/props/pi_tree1.mdl
models/man/bush_japan_group1.mdl
models/props/pi_treeb.mdl
models/props/boxsprings_wreck.mdl
models/props/mattress_wreck.mdl
models/props/shelves_warehouse.mdl
models/props/sink_small.mdl
models/props/washingmachine.mdl
models/props/bathroom_toilet_dirty.mdl
models/props/group_kitchen.mdl
models/props/toilet.mdl
models/props/furniture_group-hotel02.mdl
models/man/78rus_ladasp_orange.mdl
models/man/78rus_toyota_red.mdl
models/man/78rus_ladasp_blue.mdl
models/man/78rus_toyota.mdl
models/man/halla_antenna1a.mdl
models/props/furniture_group-hall01.mdl
models/props/furniture_group-hotel01.mdl
models/props/furniture_group-wreck.mdl
models/man/sat.mdl
models/man/unitaz.mdl
models/man/racovina.mdl
models/man/byxlo_group1.mdl
models/man/radiator.mdl
models/man/dom_school-1.mdl
sound/kvartal/car_zil.wav
models/man/dm_g_truck.mdl
models/man/nature_kust_10_group_2.mdl
models/props/bicycle_dead.mdl
models/man/buzzer_teatp_ladasp.mdl
models/man/3dm_seagull.mdl
models/props/bobik_rus-1.mdl
models/man/78rus_icarus.mdl
sprites/glow01.spr
sound/music/aria-angel.wav
sound/music/ydarnaiasila_1.wav
sound/music/travaydoma_1.wav
sound/kvartal/arcticwind.wav
models/props/truck_russian-large_blue.mdl
models/hostages/us_gal.mdl
models/hostages/npc-scientist.mdl
models/man/nature_kust_10_group_4.mdl
models/man/jed_deciduous_trees01.mdl
sound/school/dog4.wav
sound/school/city_sirenby.wav
sound/school/toruko_verynicebirdys_loop.wav
sound/school/city_loop2.wav
sound/school/fastline_station3.wav
sound/school/biolab_windoutside_loop.wav
sound/kvartal/car_siren-1.wav
sound/common/body_scream1.wav
models/man/dom_5-1.mdl
models/man/78rus_truck-zil_blue.mdl
models/man/78rus_truck-zil_yel.mdl
models/man/78rus_gazel_02.mdl
models/man/78rus_truck-zil_gray.mdl
models/man/prop_met_vanna_01.mdl
models/man/78rus_ambulance_01.mdl
maps/cs_KVARTAL2.nav
maps/cs_KVARTAL2.txt
maps/cs_KVARTAL2_detail.txt
overviews/cs_KVARTAL2.bmp
overviews/cs_KVARTAL2.txt
cs_KVARTAL2_preview.jpg
cs_KVARTAL2_ReadMe_rus.txt
cs_KVARTAL2_wallpaper_2.jpg
gfx/detail/bet_balkon_1-1.tga
gfx/detail/Brick_white_1.tga
gfx/detail/conc_asphalt_08.tga
gfx/detail/grnd_grass_003b.tga
gfx/detail/grnd_gravel_02a.tga
gfx/detail/insl_brick_2-1.tga
gfx/maps/cs_KVARTAL2_cso.tga
resource/maploading/loadingbg_cs_kvartal2.tga
maps/cs_KVARTAL2.res
