gfx/env/dustup.tga
gfx/env/dustrt.tga
gfx/env/dustdn.tga
gfx/env/dustlf.tga
gfx/env/dustbk.tga
gfx/env/dustft.tga
maps/de_tuscan_boost_final.txt
maps/de_tuscan_boost_final.res
models/de_tuscan/tuscan_shade1a.mdl
models/de_tuscan/tuscan_shade2a.mdl
models/de_tuscan/tuscan_shade3a.mdl
models/de_tuscan/tuscan_palmtree1.mdl
models/de_tuscan/tuscan_grass1a.mdl
overviews/de_tuscan_boost09.txt
overviews/de_tuscan_boost09.bmp
