//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_torn.html
sound/ambience/jetflyby1.wav
sound/ambience/drips.wav
sound/ambience/cricket.wav
sprites/xsmoke1.spr
sprites/xffloor.spr
torntextures.wad
sound/ambience/copter.wav
sound/de_torn/tk_windstreet.wav
sound/de_torn/torn_water2.wav
gfx/env/tornskybk.tga
gfx/env/tornskydn.tga
gfx/env/tornskyft.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyup.tga
sprites/xssmke1.spr
sound/de_torn/torn_ambience.wav
sprites/glow04.spr
sound/ambience/burning1.wav
sound/de_torn/torn_thndrstrike.wav
sound/de_torn/torn_bomb1.wav
sound/de_torn/torn_bomb2.wav
sound/de_torn/torn_ak-47.wav
sound/de_torn/torn_templewind.wav
sound/de_torn/torn_water1.wav
overviews/de_torn.txt
overviews/de_torn.bmp
sound/de_torn/tk_steam.wav
sound/de_torn/torn_mgun1.wav
maps/de_torn.bsp
maps/de_torn.txt
