gfx/env/mariotup.tga
gfx/env/mariotdn.tga
gfx/env/mariotlf.tga
gfx/env/mariotrt.tga
gfx/env/mariotft.tga
gfx/env/mariotbk.tga
sprites/laserbeam.spr
sound/hnsru_hell/hnsru1.wav
sound/hnsru_hell/hnsru2.wav
sound/hnsru_hell/hnsru3.wav
sound/hnsru_hell/hnsru4.wav
sound/hnsru_hell/hnsru5.wav
sound/hnsru_hell/hnsru6.wav
sound/hnsru_hell/hnsru8.wav
sound/hnsru_hell/hnsru9.wav
sound/hnsru_hell/hnsru10.wav
sound/hnsru_hell/hnsru11.wav
sound/hnsru_hell/hnsru12.wav
sound/hnsru_hell/hnsru13.wav
sound/hnsru_hell/hnsru14.wav
sound/hnsru_hell/hnsru15.wav
sound/hnsru_hell/hnsru16.wav
sound/hnsru_hell/hnsru7.wav
sound/hnsru_hell/hnsru17.wav
sound/hnsru_hell/hnsru18.wav
sound/hnsru_hell/hnsru19.wav
sound/hnsru_hell/hnsru20.wav
sound/hnsru_hell/hnsru21.wav
sound/hnsru_hell/hnsru22.wav
sound/hnsru_hell/hnsru23.wav
sound/hnsru_hell/hnsru24.wav
sound/hnsru_hell/hnsru25.wav
sound/hnsru_hell/hnsru26.wav
sound/hnsru_hell/hnsru27.wav
sound/hnsru_hell/hnsru28.wav
sound/hnsru_hell/hnsru29.wav